#!/bin/bash
usage="Extract a portion of a video (works for pure audio too)
 USAGE:
   video_extract output input start_time to end_time
   video_extract output input start_time for duration
 start and end time is in the format
 HH:MM::SS.frac
 duration is the length of the clip"

case $4 in
    "to")
        flag=-to
        ;;
    "for")
        flag=-t
        ;;
    *)
        printf "$usage"
        exit 1
        ;;
esac

ffmpeg -i "$2" -ss "$3" -codec copy $flag "$5" "$1"
        
